name: Test Docker

on: [push, workflow_dispatch]

jobs:

  builds:

    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.4.0
          - dev
        build:
          - alpine
          - amzn2
          - centos7
          - centos8
          - debian10
          - debian11-apt
          - ubuntu18-apt
          - ubuntu20
          - ubuntu22-apt
          - litespeed

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: |
          docker build --pull \
            --tag ${{ matrix.build }}-${{ matrix.version }} \
            --file docker/${{ matrix.build }}.Dockerfile .

      - name: Run tests
        env:
          SHELL: "${{ matrix.build == 'alpine' && 'sh' || 'bash' }}"
        run: |
          docker run ${{ matrix.build }}-${{ matrix.version }} $SHELL -c "php --ri relay"
